base_config:
- config/logging.yaml
- config/wandb.yaml
- config/dataset/dataset_da_sam_train.yaml
- config/dataset/dataset_da_sam_val.yaml
- config/dataset/dataset_da_sam_vis.yaml

model:
  name: InvisibleStitch
  kwargs:
    loss_stategy: 'entire_scene'

depth_normalization:
  type: sam_depth

augmentation:
  lr_flip_p: 0.5

dataloader:
  num_workers: 8
  effective_batch_size: 32
  max_train_batch_size: 8
  seed: 2024  # to ensure continuity when resuming from checkpoint

# Training settings
trainer:
  name: InvisibleStitchTrainer
  init_seed: 2024  # use null to train w/o seeding
  save_period: 20000
  backup_period: 20000
  validation_period: 10000
  visualization_period: 10000
  max_grad_norm: 0.01
  w_occ: 0.7
  loss_stategy: entire_scene
  mixed_precision: 'no'

gt_depth_type: depth_gt
gt_mask_type: valid_mask_raw

max_epoch: 60000  # a large enough number
max_iter: 60000  # usually converges at around 20k

optimizer:
  name: Adam

loss:
  # name: mse_loss
  name: silog_loss
  kwargs:
    beta: 0.15

lr: 3.0e-05
scale_lr: 1
lr_scheduler:
  name: IterExponential
  kwargs:
    total_iter: 50000
    final_ratio: 0.01
    warmup_steps: 100

# Validation (and visualization) settings
validation:
  denoising_steps: 50
  ensemble_size: 1  # simplified setting for on-training validation
  processing_res: 0
  match_input_res: false
  resample_method: bilinear
  main_val_metric: abs_relative_difference
  main_val_metric_goal: minimize
  init_seed: 2024

eval:
  alignment: least_square
  align_max_res: null
  eval_metrics:
  - abs_relative_difference
  - squared_relative_difference
  - rmse_linear
  - rmse_log
  - log10
  - delta1_acc
  - delta2_acc
  - delta3_acc
  - i_rmse
  - silog_rmse